-- ---------------------------------------------------------------------------
-- Sistema CTI Insights - esquema do banco (PostgreSQL / Azure Database for PostgreSQL)
--
-- O Hibernate cria as tabelas sozinho (spring.jpa.hibernate.ddl-auto=update),
-- mas este arquivo e a documentacao oficial do modelo: e o que a banca le para
-- entender o desenho e o que permite recriar o banco do zero em outro provedor.
--
-- Execucao:  psql "$DB_URL" -f schema.sql
-- ---------------------------------------------------------------------------

DROP TABLE IF EXISTS telemetria CASCADE;
DROP TABLE IF EXISTS insight CASCADE;
DROP TABLE IF EXISTS contrato CASCADE;
DROP TABLE IF EXISTS cliente CASCADE;
DROP TABLE IF EXISTS servico CASCADE;
DROP TABLE IF EXISTS consultor CASCADE;

-- ---------------------------------------------------------------------------
-- Consultor: 1 consultor -> N clientes
-- ---------------------------------------------------------------------------
CREATE TABLE consultor (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      VARCHAR(120) NOT NULL UNIQUE,
    matricula VARCHAR(40) UNIQUE
);

-- ---------------------------------------------------------------------------
-- Cliente: nucleo da carteira comercial
-- codigo_cti e a chave de negocio (o codigo interno usado pela CTI na planilha)
-- ---------------------------------------------------------------------------
CREATE TABLE cliente (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_cti        VARCHAR(40)  NOT NULL UNIQUE,
    segmento          VARCHAR(80)  NOT NULL,
    nivel             CHAR(1)      NOT NULL,
    faturamento_anual NUMERIC(15, 2),
    consultor_id      BIGINT REFERENCES consultor (id) ON DELETE SET NULL,
    CONSTRAINT ck_cliente_nivel CHECK (nivel IN ('A', 'B', 'C')),
    CONSTRAINT ck_cliente_faturamento CHECK (faturamento_anual IS NULL OR faturamento_anual >= 0)
);

-- ---------------------------------------------------------------------------
-- Servico: catalogo da CTI (link dedicado, cloud, telefonia...)
-- ---------------------------------------------------------------------------
CREATE TABLE servico (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      VARCHAR(120) NOT NULL UNIQUE,
    categoria VARCHAR(60)
);

-- ---------------------------------------------------------------------------
-- Contrato: 1 cliente -> N contratos ; N contratos -> 1 servico
-- ---------------------------------------------------------------------------
CREATE TABLE contrato (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_inicio DATE        NOT NULL,
    status      VARCHAR(12) NOT NULL DEFAULT 'ATIVO',
    cliente_id  BIGINT      NOT NULL REFERENCES cliente (id) ON DELETE CASCADE,
    servico_id  BIGINT      NOT NULL REFERENCES servico (id),
    CONSTRAINT ck_contrato_status CHECK (status IN ('ATIVO', 'ENCERRADO', 'SUSPENSO'))
);

-- ---------------------------------------------------------------------------
-- Insight: heranca de tabela unica (SINGLE_TABLE).
-- A coluna "tipo" e o discriminador; cada subtipo usa apenas as suas colunas.
-- ---------------------------------------------------------------------------
CREATE TABLE insight (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo                    VARCHAR(20)  NOT NULL,
    descricao               VARCHAR(400) NOT NULL,
    gerado_em               TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cliente_id              BIGINT REFERENCES cliente (id) ON DELETE CASCADE,
    -- InsightSegmento
    segmento                VARCHAR(80),
    participacao_percentual DOUBLE PRECISION,
    -- InsightFaturamento
    faturamento_medio       NUMERIC(15, 2),
    faturamento_mediano     NUMERIC(15, 2),
    -- InsightServico
    servico_nome            VARCHAR(120),
    total_contratos         INTEGER,
    CONSTRAINT ck_insight_tipo CHECK (tipo IN ('SEGMENTO', 'FATURAMENTO', 'SERVICO'))
);

-- ---------------------------------------------------------------------------
-- Telemetria: trilha de uploads e execucoes do modulo Python
-- ---------------------------------------------------------------------------
CREATE TABLE telemetria (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento     VARCHAR(60)  NOT NULL,
    status     VARCHAR(20)  NOT NULL,
    detalhe    VARCHAR(500),
    duracao_ms BIGINT,
    timestamp  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- Indices: sustentam os filtros e agrupamentos do dashboard
-- ---------------------------------------------------------------------------
CREATE INDEX idx_cliente_segmento    ON cliente (segmento);
CREATE INDEX idx_cliente_nivel       ON cliente (nivel);
CREATE INDEX idx_cliente_consultor   ON cliente (consultor_id);
CREATE INDEX idx_contrato_cliente    ON contrato (cliente_id);
CREATE INDEX idx_contrato_servico    ON contrato (servico_id);
CREATE INDEX idx_contrato_data       ON contrato (data_inicio);
CREATE INDEX idx_insight_gerado_em   ON insight (gerado_em DESC);
CREATE INDEX idx_telemetria_momento  ON telemetria (timestamp DESC);

-- ---------------------------------------------------------------------------
-- Consultas de referencia (as mesmas que a API expoe em /api/indicadores)
-- ---------------------------------------------------------------------------

-- Clientes por segmento
-- SELECT segmento, COUNT(*) AS clientes
--   FROM cliente GROUP BY segmento ORDER BY clientes DESC;

-- Distribuicao por nivel, em percentual da carteira
-- SELECT nivel,
--        COUNT(*) AS clientes,
--        ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 1) AS percentual
--   FROM cliente GROUP BY nivel ORDER BY nivel;

-- Servicos mais contratados
-- SELECT s.nome, COUNT(*) AS contratos
--   FROM contrato c JOIN servico s ON s.id = c.servico_id
--  GROUP BY s.nome ORDER BY contratos DESC;

-- Evolucao mensal das contratacoes
-- SELECT TO_CHAR(data_inicio, 'YYYY-MM') AS mes, COUNT(*) AS contratos
--   FROM contrato GROUP BY 1 ORDER BY 1;

-- Faturamento medio e mediano por segmento
-- SELECT segmento,
--        ROUND(AVG(faturamento_anual), 2) AS media,
--        PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY faturamento_anual) AS mediana
--   FROM cliente WHERE faturamento_anual IS NOT NULL GROUP BY segmento;
